### ISSUE TITLE
a terrible crash bug!

### ISSUE THREAD

**Issue by yychai** [BiaoWu/Android-Pull-To-Refresh#3]
in your demo, pull down to refresh first, and then pull up to load more, and 3rd step, pull down to refresh, then you ptrLayout crashed!! please fix it .

**Comment by zyyoona7** [comment]
我也发现这个问题
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 20(offset:20).state:40
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4405)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
                                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at com.biao.pulltorefresh.PtrLayout.layoutChild(PtrLayout.java:168)
                                                                                 at com.biao.pulltorefresh.PtrLayout.onLayout(PtrLayout.java:136)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                 at com.android.internal.policy.impl.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3506)
                                                                                 at android.view.View.layout(View.java:15746)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5040)
                                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2162)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1919)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1136)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6037)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispa
